dt: 0.002
decimation: 4
num_of_dofs: 12

fixed_kp: [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0]
fixed_kd: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
torque_limits: [23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5, 23.5]

# q_motor = q_joint * joint_transmission_ratio[i]
# calves (2/5/8/11): base 6.33 with extra 7/3 reducer => 14.77
joint_transmission_ratio: [6.33, 6.33, 14.77, 6.33, 6.33, 14.77, 6.33, 6.33, 14.77, 6.33, 6.33, 14.77]

default_dof_pos: [-0.35, 0.99, -2.57, 0.35, 0.99, -2.57, -0.35, 0.99, -2.57, 0.35, 0.99, -2.57]
standup_target_pos: [-0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 0.8, -1.5]
policy_dof_pos: [-0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 0.8, -1.5]

joint_pos_lower: [-0.8, -1.04, -2.69, -0.8, -1.04, -2.69, -0.8, -1.04, -2.69, -0.8, -1.04, -2.69]
joint_pos_upper: [0.8, 4.18, -0.91, 0.8, 4.18, -0.91, 0.8, 4.18, -0.91, 0.8, 4.18, -0.91]

joint_names: ["FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint", "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint"]
joint_controller_names: ["FR_hip", "FR_thigh", "FR_calf", "FL_hip", "FL_thigh", "FL_calf", "RR_hip", "RR_thigh", "RR_calf", "RL_hip", "RL_thigh", "RL_calf"]
# policy DOF index -> motor id
joint_mapping: [1, 2, 3, 4, 5, 6, 10, 11, 12, 7, 8, 9]
wheel_indices: []

policy_path: policy/policy.pt
device: cuda:0
port0: /dev/motor_front
port1: /dev/motor_rear
imu_topic: /fast_livo2/state6
robot_name: mybot_v2
urdf_relpath: robot/mybot_v2/urdf/mybot_v2.urdf
mujoco_xml_relpath: robot/mybot_v2/xml/mybot_v2_for_mujoco.xml
isaac_xml_relpath: robot/mybot_v2/xml/mybot_v2_for_isaacgym.xml

kp_joint: 80.0
kd_joint: 2.0
kd_damp_motor: 0.1

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
dof_vel_scale: [0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]
action_scale: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]

cmd_deadband: 0.05
control_dt: 0.02
standup_duration: 2.0
